version: '3'
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - "90:80"
      - "8000:8000"
      - "8020:8020"
      - "8040:8040"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql@sha256:4cb929cd5b89f157284f0572feff652af31e4e29db3c3eb32565d6e3bce0fa84
    environment:
      MYSQL_DATABASE: elearning
      MYSQL_USER: globalituser
      MYSQL_PASSWORD: GlobalIT@123
      MYSQL_ROOT_PASSWORD: GlobalIT@123
    ports:
      - "3313:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:



